-- Ajouter les nouvelles colonnes sans la contrainte NOT NULL
ALTER TABLE EMPLOYEE ADD id NUMBER(9);
ALTER TABLE EMPLOYEE ADD posid NUMBER(9);
ALTER TABLE EMPLOYEE ADD departid NUMBER(5);
ALTER TABLE EMPLOYEE ADD email VARCHAR2(45);
ALTER TABLE EMPLOYEE ADD gender VARCHAR2(35);
ALTER TABLE EMPLOYEE ADD joindate DATE;
ALTER TABLE EMPLOYEE ADD city VARCHAR2(35);
ALTER TABLE EMPLOYEE ADD address VARCHAR2(35);
ALTER TABLE EMPLOYEE ADD phone VARCHAR2(35);
