SELECT p.PARTICIPATIONID, 
       p.ACTIVITYID, 
       p.CLIENTID, 
       p.PARTICIPATIONDATE 
FROM PARTICIPATION p 
WHERE p.PARTICIPATIONDATE BETWEEN TO_DATE('start_date', 'DD/MM/YYYY') AND TO_DATE('end_date', 'DD/MM/YYYY');
