CREATE TABLE ACTIVITY (
    ACTIVITYID INTEGER NOT NULL,
    ACTIVITYNAME VARCHAR2(50) NOT NULL,
    DESCRIPTION VARCHAR2(255),
    STARTDATE DATE,
    ENDDATE DATE,
    HOTELID INTEGER,
    PRIMARY KEY (ACTIVITYID)
);

CREATE TABLE CLIENT (
    CLIENTID INTEGER NOT NULL,
    NAME VARCHAR2(50) NOT NULL,
    EMAIL VARCHAR2(50),
    PHONE VARCHAR2(15),
    PRIMARY KEY (CLIENTID)
);

CREATE TABLE EMPLOYEE (
    EMPLOYEEID INTEGER NOT NULL,
    NAME VARCHAR2(50) NOT NULL,
    EMAIL VARCHAR2(50),
    PHONE VARCHAR2(15),
    HIRE_DATE DATE,
    PRIMARY KEY (EMPLOYEEID)
);

CREATE TABLE HOTEL (
    HOTELID INTEGER NOT NULL,
    HOTELNAME VARCHAR2(50) NOT NULL,
    LOCATION VARCHAR2(50),
    RATING INTEGER,
    PRIMARY KEY (HOTELID)
);

CREATE TABLE PARTICIPATESIN (
    PARTICIPATIONID INTEGER NOT NULL,
    ACTIVITYID INTEGER,
    CLIENTID INTEGER,
    PARTICIPATIONDATE DATE,
    PRIMARY KEY (PARTICIPATIONID)
);

CREATE TABLE PARTICIPATION (
    PARTICIPATIONID INTEGER NOT NULL,
    ACTIVITYID INTEGER,
    CLIENTID INTEGER,
    PARTICIPATIONDATE DATE,
    PRIMARY KEY (PARTICIPATIONID)
);

CREATE TABLE RESERVATION (
    RESERVATIONID INTEGER NOT NULL,
    CLIENTID INTEGER,
    HOTELID INTEGER,
    CHECKINDATE DATE,
    CHECKOUTDATE DATE,
    PRIMARY KEY (RESERVATIONID)
);
